import { NgModule } from '@angular/core';
import {
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatNativeDateModule,
    MatDatepickerModule,
    MatDividerModule,
    MatSidenavModule,
    MatListModule,
    MatTooltipModule,
    MatButtonModule,
    MatToolbarModule,
    MatIconModule,
    MatTableModule,
    MatCheckboxModule,
    MatInputModule,
    MatSelectModule,
    MatSnackBarModule,
    MatTabsModule,
    MatMenuModule,
    MatExpansionModule,
    MatDialogModule,
    MatFormFieldModule,
    MatPaginatorModule,
    MatCardModule
} from '@angular/material'

@NgModule({

    imports: [
        MatProgressBarModule,
        MatToolbarModule,
        MatProgressSpinnerModule,
        MatNativeDateModule,
        MatDatepickerModule,
        MatDividerModule,
        MatListModule,
        MatSidenavModule,
        MatSnackBarModule,
        MatTooltipModule,
        MatButtonModule,
        MatToolbarModule,
        MatIconModule,
        MatTableModule,
        MatCheckboxModule,
        MatInputModule,
        MatSelectModule,
        MatTabsModule,
        MatMenuModule,
        MatExpansionModule,
        MatDialogModule,
        MatFormFieldModule,
        MatPaginatorModule,
        MatCardModule
        
    ],
    exports: [
        MatProgressBarModule,
        MatToolbarModule,
        MatProgressSpinnerModule,
        MatNativeDateModule,
        MatDividerModule,
        MatDatepickerModule,
        MatListModule,
        MatSnackBarModule,
        MatSidenavModule,
        MatTooltipModule,
        MatButtonModule,
        MatToolbarModule,
        MatIconModule,
        MatTableModule,
        MatCheckboxModule,
        MatInputModule,
        MatSelectModule,
        MatTabsModule,
        MatMenuModule,
        MatExpansionModule,
        MatDialogModule,
        MatFormFieldModule,
        MatPaginatorModule,
        MatCardModule,
        
    ],
})
export class MaterialModule { }